export const languages = [
    ["arm", /.*arm/i],
    ["cpp", /.*c(\+\+|pp)/i],
    ["css", /.*css/i],
    ["cs", /.*c(sharp|#|s)/i],
    ["c", /.*c/i],
    ["glsl", /.*glsl/i],
    ["hlsl", /.*hlsl/i],
    ["jai", /.*jai/i],
    ["js", /.*(js|javascript)/i],
    ["java", /.*java/i],
    ["jsonc", /.*jsonc/i],
    ["json", /.*json/i],
    ["lua", /.*lua/i],
    ["makefile", /.*make(file)?/i],
    ["python", /.*py(thon)?/i],
    ["shaderlab", /.*shaderlab/i],
    ["sql", /.*sql/i],
    ["toml", /.*toml/i],
    ["ts", /.*(ts|typescript)/i],
    ["vdf", /.*(vdf|valve)/i],
    ["x64", /.*x(86_)?64/i],
    ["yaml", /.*yaml/i],
    ["html", /.*x?html/i],
    ["md", /.*(md|markdown)/i],
    ["xml", /.*xml/i],
    ["xsl", /.*xsl/i],
];
